### ISSUE TITLE
Định nghĩa max rồi tại sao lại vẫn để số 5 tại đây ? 

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/2D_Array_Becodeching#1]
https://github.com/thoaikhoa14402/2D_Array_Becodeching/blob/a200a43c4eba4ac93d6ec9820318ead64c6a702f/Hi%E1%BB%83n%20th%E1%BB%8B%20ma%20tr%E1%BA%ADn%20theo%20y%C3%AAu%20c%E1%BA%A7u.cpp#L9

**Comment by thoaikhoa14402** [comment]
dạ e quên ạ
