### ISSUE TITLE
Với trường hợp n = 5 thì có thể in ra tam giác pascal (nhưng ở đây output ra như tam giác vuông vậy). Vậy với trường hợp n = 100 thì chắc chắn lời giải sẽ bị có vấn đề

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/2D_Array_Becodeching#2]
https://github.com/thoaikhoa14402/2D_Array_Becodeching/blob/a200a43c4eba4ac93d6ec9820318ead64c6a702f/Tam%20gi%C3%A1c%20pascal.cpp#L16

**Comment by thoaikhoa14402** [comment]
![image](https://user-images.githubusercontent.com/81000230/115698171-87905a00-a38e-11eb-8771-a3225c794407.png)
thế thì mình chỉ cần chỉnh lại thành kiểu long long là dc thôi ạ
