### ISSUE TITLE
Biến này dùng để làm gì vậy ? Ma trận cấp phát bộ nhớ như vậy nếu như nó chưa được sử dụng hết thì nên làm cách nào để tránh bị lãng phí memory ? 

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/2D_Array_Becodeching#3]
https://github.com/thoaikhoa14402/2D_Array_Becodeching/blob/a200a43c4eba4ac93d6ec9820318ead64c6a702f/T%E1%BB%95ng%20c%C3%A1c%20s%E1%BB%91%20l%E1%BA%BB%20%E1%BB%9F%20%C4%91%C6%B0%E1%BB%9Dng%20ch%C3%A9o%20ch%C3%ADnh%20v%C3%A0%20ph%E1%BB%A5.cpp#L70

**Comment by thoaikhoa14402** [comment]
2 biến đó là trong code cũ em quên delete ấy ạ, nếu muốn tránh lãng phí thì dùng con trỏ cấp 2 để quản lí mảng 2 chiều, cách đó thì cũng dễ nhưng mà em viết kiểu này cho nhanh thôi ạ

**Comment by toniminh161200** [comment]
Để nhanh liệu sau này bạn vào làm trong 1 công ty rồi viết để nhanh thì có ý nghĩa gì k bạn ?

**Comment by thoaikhoa14402** [comment]
Dạ v nếu tránh lãng phí  ta có thể làm như sau: ma trận có n dòng , m cột ==> tạo một con trỏ cấp 2 quản lý mảng con trỏ dòng, mỗi con trỏ dòng lại cấp phát m cột. Sau cùng là phải giải phóng từng con trỏ dòng, và giải phóng con trỏ cấp 2 quản lý mảng con trỏ dòng
